config/routes.rb
Rails.application.routes.draw do
  resources :expenses
  root 'home#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :expenses
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :category

  validates :title, presence: true
  validates :amount, presence: true
  validates :amount, numericality: { greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :log_session_id
  before_action :set_p3p

  def set_p3p
    response.headers["P3P"]='CP="CAO PSA OUR"'
  end

  def log_session_id
    logger.info '  Session ID: ' + (request.session_options[:id] || 'N/A')
  end
  
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.all.order(created_at: :desc)
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to action: "index", notice: 'Expense was successfully created.' }
        format.json { render :index, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to action: "index", notice: 'Expense was successfully updated.' }
        format.json { render :index, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:title, :amount, :category_id, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @expenses = Expense.where("created_at > ?", 7.days.ago)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/expenses/_form.html.erb
<%= form_with(model: expense, local: true) do |form| %>
  <% if expense.errors.any? %>
    <div id="error_explanation" class="errors-wrapper">
      <h4 class="title"><%= t('.errors_title') %></h4>

      <ul>
      <% expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <span class="label"><%= form.label :title, t('.title') %></span>
    <span class="input-wrapper"><%= form.text_field :title %></span>
  </div>

  <div class="field">
    <span class="label"><%= form.label :amount, t('.amount') %></span>
    <span class="input-wrapper"><%= form.number_field :amount, step: "any" %></span>
  </div>

  <div class="field">
    <span class="label"><%= form.label :category_id, t('.category') %></span>
    <span class="input-wrapper custom-dropdown"><%= collection_select(:expense, :category_id, Category.all, :id, :title, prompt: true) %></span>
  </div>

  <div class="field">
    <span class="label"><%= form.label :description, t('.Description') %></span>
    <span class="input-wrapper"><%= form.text_area :description %></span>
  </div>

  <div class="actions">
    <%#= form.submit do %>
        <%#= fa_icon "pen", text: t('.submit') %>
    <%# end %>
    <%= button_tag type: 'submit', class: 'primary-button' do %>
        <%= fa_icon "check", text: t('.submit') %>
    <% end %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<div class="form-wrapper">
  <h2><%= t('.title') %></h2>

  <%= render 'form', expense: @expense %>

  <%= link_to expenses_path, class: 'secondary-button return-button' do %>
      <%= fa_icon "chevron-left", text: t('.back') %>
  <% end %>
</div>

app/views/expenses/index.html.erb
<h1><%= t('.title') %></h1>

<%= link_to new_expense_path, class: 'primary-button' do %>
    <%= fa_icon "plus", text: t('.new_entry') %>
<% end %>

<div class="expenses-list-wrapper">
  <div class="list-header">
    <div class="header-field title label"><%= t('.expense_title') %></div>
    <div class="header-field amount label"><%= t('.amount') %></div>
    <div class="header-field category label"><%= t('.category') %></div>
    <div class="header-field description label"><%= t('.description') %></div>
    <div class="header-field date label"><%= t('.date') %></div>
    <div class="header-field actions label"></div>
  </div>

  <div class="list-body">
    <% @expenses.each do |expense| %>
        <div class="fields-wrapper">
          <div class="field title data"><span class="mobile-title"><%= t('.expense_title') %></span> <span class="text"><%= expense.title %></span></div>
          <div class="field amount data"><span class="mobile-title"><%= t('.amount') %></span> <span class="text"><%= number_to_currency expense.amount, locale: :hr %></span></div>
          <div class="field category data"><span class="mobile-title"><%= t('.category') %></span> <span class="text"><%= expense.category.title %></span></div>
          <div class="field description data"><span class="mobile-title"><%= t('.description') %></span> <span class="text"><%= expense.description %></span></div>
          <div class="field date data"><span class="mobile-title"><%= t('.date') %></span> <span class="text"><%= l expense.created_at %></span></div>
          <div class="field actions data">
            <%= link_to edit_expense_path(expense), class: 'primary-button' do %>
                <%= fa_icon "edit", text: t('.edit') %>
            <% end %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/expenses/new.html.erb
<div class="form-wrapper">
  <h2><%= t('.title') %></h2>

  <%= render 'form', expense: @expense %>

  <%= link_to expenses_path, class: 'secondary-button return-button' do %>
      <%= fa_icon "chevron-left", text: t('.back') %>
  <% end %>
</div>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @expense.title %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @expense.amount %>
</p>

<p>
  <strong>Category:</strong>
  <%= @expense.category.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @expense.description %>
</p>

<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>

app/views/home/index.html.erb
<section class="description">
  <h1><%= t('.description_title') %></h1>

  <p><%= t('.description_body') %></p>

  <div class="background"></div>
</section>

<section class="last-week-expenses-wrapper">
  <h2><%= t('.last_week_expenses') %></h2>

  <%= link_to new_expense_path, class: 'primary-button' do %>
      <%= fa_icon "plus", text: t('.new_entry') %>
  <% end %>

  <div class="expenses-list-wrapper">
    <% if @expenses.any? %>
      <div class="list-header">
        <div class="header-field title label"><%= t('.name') %></div>
        <div class="header-field description label"><%= t('.description') %></div>
        <div class="header-field amount label"><%= t('.amount') %></div>
        <div class="header-field date label"><%= t('.time') %></div>
      </div>
      <div class="list-body">
        <% @expenses.each do |expense| %>
            <div class="fields-wrapper">
              <div class="field title data"><span class="mobile-title"><%= t('.name') %></span> <span class="text"><%= expense.title %></span></div>
              <div class="field description data"><span class="mobile-title"><%= t('.description') %></span> <span class="text"><%= expense.description %></span></div>
              <div class="field amount data"><span class="mobile-title"><%= t('.amount') %></span> <span class="text"><%= number_to_currency expense.amount, locale: :hr %></span></div>
              <div class="field date data"><span class="mobile-title"><%= t('.time') %></span> <span class="text"><%= l expense.created_at %></span></div>
            </div>
        <% end %>
      </div>
    <% else %>
      <p><%= t('.no_expenses') %></p>
    <% end %>
  </div>
</section>

app/views/layouts/_header.html.erb
<header>
  <%= link_to t('.home'), root_path, class: 'logo' %>

  <nav>
    <%= link_to t('.home'), root_path, class: "navigation-link primary-button #{ 'active' if controller_name == 'home'}" %>
    <%= link_to t('.expenses'), expenses_path, class: "navigation-link primary-button #{ 'active' if controller_name == 'expenses' && action_name == 'index' }" %>
    <%#= link_to t('.log_out'), '#', class: 'navigation-link secondary-button' %>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t('.title') %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    '/fonts/stylesheet.css', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= yield :head %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <%= render_google_analytics_script %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <%= render 'layouts/header' %>

    <div class="content">
      <%= yield %>
    </div>
  </body>
</html>